import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import ssl_fix  # noqa

'''
Streamlit Research Tool — Powered by HuggingFace

This app loads a saved PromptTemplate (ml_template.json) generated by
prompt_generator.py and uses it to explain ML algorithms via the HF API.

Loading the template from JSON rather than redefining it here demonstrates
the decoupled workflow: one module owns the template definition, another
owns the UI and execution logic.

Run with: streamlit run prompts/research_tool.py
NOTE: Run prompt_generator.py first to create ml_template.json
'''

import streamlit as st
from dotenv import load_dotenv
load_dotenv()

if not os.getenv("HUGGINGFACEHUB_API_TOKEN"):
    st.error("HuggingFace API token not found. Add HUGGINGFACEHUB_API_TOKEN to your .env file.")
    st.stop()

from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from langchain_core.prompts import load_prompt
from langchain_core.output_parsers import StrOutputParser

# ── UI ────────────────────────────────────────────────────────────────────
st.title("ML Algorithm Explainer")
st.markdown("Pick an algorithm and customise how you want it explained.")

algorithm_options = [
    "Gradient Boosting (XGBoost / LightGBM)",
    "Transformer Attention Mechanism",
    "Variational Autoencoder (VAE)",
    "Reinforcement Learning - Policy Gradient",
]
selected_algo = st.selectbox("Select an ML Algorithm", algorithm_options)

style_options = ["Beginner-friendly with analogies", "Math-heavy", "Code-heavy"]
selected_style = st.selectbox("Teaching Style", style_options)

length_options = ["Short (< 100 words)", "Medium (200-300 words)", "Long (500+ words)"]
selected_length = st.selectbox("Response Length", length_options)

# ── Logic ─────────────────────────────────────────────────────────────────
if st.button("Explain"):
    with st.spinner("Generating explanation via HuggingFace..."):
        try:
            template_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "ml_template.json")
            prompt_template = load_prompt(template_path)

            llm = HuggingFaceEndpoint(
                repo_id="Qwen/Qwen2.5-7B-Instruct",
                huggingfacehub_api_token=os.getenv("HUGGINGFACEHUB_API_TOKEN"),
                max_new_tokens=512,
                temperature=0.4,
                task="conversational",
            )
            model = ChatHuggingFace(llm=llm)
            parser = StrOutputParser()

            formatted_prompt = prompt_template.format(
                algorithm=selected_algo,
                style=selected_style,
                length=selected_length,
            )

            response = model.invoke(formatted_prompt)

            st.markdown("### Explanation")
            st.write(parser.invoke(response))

        except Exception as e:
            st.error(f"Something went wrong: {e}")
